export const SET_RESOURCES = 'SET_RESOURCES';

export const GET_REGIONS = 'GET_REGIONS';
export const GET_REGIONS_RECIEVED = 'GET_REGIONS_RECIEVED';

export const GET_DISTRICTS = 'GET_DISTRICTS';
export const GET_DISTRICTS_RECIEVED = 'GET_DISTRICTS_RECIEVED';

export const GET_CITIES = 'GET_CITIES';
export const GET_CITIES_RECIEVED = 'GET_CITIES_RECIEVED';

export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_RECIEVED = 'GET_QUESTIONS_RECIEVED';

export const SET_DEFAULT_ANSWERS = 'SET_DEFAULT_ANSWERS';
export const SET_ANSWER = 'SET_ANSWER';